default_install_hook_types = ["pre-commit", "pre-push"]
orphan = true
default_stages = ["pre-commit"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "go-lint"
name = "go lint"
entry = "just lint"
language = "system"
files = "\\.go$"
pass_filenames = false

[[repos.hooks]]
id = "go-format"
name = "go format"
entry = "just format"
language = "system"
files = "\\.go$"
pass_filenames = false

[[repos.hooks]]
id = "gopls"
name = "gopls diagnostics"
entry = "./scripts/gopls-check.sh"
language = "system"
files = "\\.go$"
pass_filenames = true
priority = 20

[[repos.hooks]]
id = "go-test"
name = "go test"
entry = "just test"
language = "system"
stages = ["pre-push"]
pass_filenames = false


[[repos.hooks]]
id = "validate-fly-config"
name = "Validate Fly config"
entry = "fly config validate"
language = "system"
stages = ["pre-commit"]
files = "fly.toml"
pass_filenames = false
