app = "pro-fm-whisper"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  WHISPER_MODEL = "base"
  UVICORN_HOST = "::"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
