app = "pro-fm-whisper"
primary_region = "fra"

[build]
dockerfile = "Dockerfile"

[env]
UVICORN_HOST = "0.0.0.0"
ENABLE_UI = "false"
WHISPER__MODEL = "base"
WHISPER__COMPUTE_TYPE = "int8"
PRELOAD_MODELS = '["base"]'
DEFAULT_LANGUAGE = "ro"
OMP_NUM_THREADS = "4"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[http_service.checks]]
grace_period = "90s"
interval = "15s"
timeout = "5s"
method = "GET"
path = "/health"
