default:
    just -l
build:
    go build -o pro-fm-poller ./cmd/pro-fm-poller

run: build
    ./pro-fm-poller

test:
    go test -v ./pkg/...

test-e2e:
    go test -v -tags=e2e ./pkg/...

lint:
    ./scripts/golangci-lint-shim.sh run

test-cover:
    go test -coverprofile=coverage.out ./pkg/...
    go tool cover -func=coverage.out

test-cover-html: test-cover
    go tool cover -html=coverage.out
