default_install_hook_types = ["pre-commit", "pre-push"]
orphan = true
default_stages = ["pre-commit"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "go-lint"
name = "go lint"
entry = "./scripts/golangci-lint-shim.sh run"
language = "system"
files = "\\.go$"
pass_filenames = false

[[repos.hooks]]
id = "go-format"
name = "go format"
entry = "go fmt ./..."
language = "system"
files = "\\.go$"
pass_filenames = false

[[repos.hooks]]
id = "go-test"
name = "go test"
entry = "go test ./pkg/..."
language = "system"
stages = ["pre-push"]
pass_filenames = false


