default_install_hook_types = ["pre-commit", "pre-push"]
orphan = true
default_stages = ["pre-commit"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "go-lint"
name = "go lint"
entry = "just -f pe-bune/justfile -d pe-bune lint"
language = "system"
files = "\\.go$"
pass_filenames = false

[[repos.hooks]]
id = "go-format"
name = "go format"
entry = "just -f pe-bune/justfile -d pe-bune format"
language = "system"
files = "\\.go$"
pass_filenames = false

[[repos.hooks]]
id = "go-test"
name = "go test"
entry = "just -f pe-bune/justfile -d pe-bune test"
language = "system"
stages = ["pre-push"]
pass_filenames = false


